### PR TITLE
Multi-language documentation for Quickstart example

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Comment by wetted** [comment]
@sdelamo @timyates I'm puzzled why the test-suite test case fails. It passes locally for me every time. Ugh.

**Comment by sdelamo** [comment]
it was failing for me locally as well. I have fixed the tests.

**Review by sdelamo — APPROVED** [review]

**Comment by timyates** [comment]
I still think

```
    static {
        MY_KAFKA = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:latest"))
        MY_KAFKA.start()
    }
```

Is an anti-pattern especially in Spock tests

**Comment by sdelamo** [comment]
> I still think
> 
> ```
>     static {
>         MY_KAFKA = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:latest"))
>         MY_KAFKA.start()
>     }
> ```
> 
> Is an anti-pattern especially in Spock tests

Please, @timyates send an additional PR.

**Comment by timyates** [comment]
https://github.com/micronaut-projects/micronaut-kafka/pull/824

👍

**Comment by wetted** [comment]
#825

**Pull request merged**
