### PR TITLE
Opentelemetry integration

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher @sdelamo Hi! Could you review PR?

**Comment by dstepanov** [comment]
It looks fine to me. I think maybe this should be added in https://github.com/micronaut-projects/micronaut-tracing/ ?
WDYT @graemerocher @sdelamo @n0tl3ss ?

It reminds me it would be nice to remove old tracing stuff in the next major version.

**Comment by donbeave** [comment]
There are already two extensions for the OTEL module in micronaut-opentelemetry:

1) https://github.com/micronaut-projects/micronaut-tracing/tree/master/tracing-opentelemetry-grpc
2) https://github.com/micronaut-projects/micronaut-tracing/tree/master/tracing-opentelemetry-http

From my point of view, it makes sense to make another one `tracing-opentelemetry-kafka`.

**Review by donbeave — COMMENTED** [review]
Maybe instead of using `kafka.otel.enabled` and `kafka.otel.captured-headers` can reuse already existed:

`otel.instrumentation.kafka.enabled` and `otel.instrumentation.messaging.experimental.capture-headers`?

**Comment by altro3** [comment]
@dstepanov @n0tl3ss @donbeave done. See https://github.com/micronaut-projects/micronaut-tracing/pull/199

**Pull request closed without merging**
