### PR TITLE
Support custom timestamp for ProducerRecord. Closes #63

### LINKED ISSUE #63: Custom timestamp for ProducerRecord
Hello,

I'm trying to provide my custom timestamp value for the KafkaClient. 
But it can't be done since it is just a boolean flag and in `KafkaClientIntroductionAdvice.buildProducerRecord` it's just a ternary operator with `System.currentTimeMillis()` or `null`:
```
private ProducerRecord buildProducerRecord(AnnotationValue<KafkaClient> client, String topic, List<Header> kafkaHeaders, Object key, Object value) {
    return new ProducerRecord(
            topic,
            null,
            client.getRequiredValue("timestamp", Boolean.class) ? System.currentTimeMillis() : null,
            key,
            value,
            kafkaHeaders.isEmpty() ? null : kafkaHeaders
    );
}
```
I would like to add support for this, probably by adding new annotation like @KafkaKey.
How does that sound to you?

### PR DESCRIPTION
**Pull request by finke-ba**
Hello, @graemerocher. 
This PR closes #63.
Waiting for you comments!

### CODE REVIEW

**Comment by finke-ba** [comment]
Failing test is not related to my changes - `io.micronaut.configuration.kafka.streams.KafkaStreamsSpec`

**Comment by graemerocher** [comment]
@finke-ba Thanks yes, sometimes Travis runs low on memory causing test failures. As for the change it looks fine, although this raises the issue that I think we need to alter the code to build all of the applicable arguments in one go. Currently we are looping over arguments searching for `@KafkaKey`, the `@Topic` and now with this change `@KafkaTimestamp` for each annotation and really for performance we should loop only once. Maybe that is a separate optimization however

**Comment by finke-ba** [comment]
@graemerocher yes, that's true, also for `@Body` and `@Header`.
I think it should be another task and I could do it, as I'm already in this context.
And I was thinking about unit tests for KafkaClientIntroductionAdvice, it's missing at the moment, but logic in intercept method is complicated.

**Comment by graemerocher** [comment]
Yes it is evolved over time and has reached the point where some refactoring work is needed to make it more maintainable and performant. If you wish to have a look contributions are 100% welcome.

**Comment by finke-ba** [comment]
> Yes it is evolved over time and has reached the point where some refactoring work is needed to make it more maintainable and performant. If you wish to have a look contributions are 100% welcome.

Should I create issue for that or just provide PR?

**Comment by graemerocher** [comment]
Just a PR is good. Thanks for the contribution

**Pull request merged**
