### PR TITLE
GH-347 kafka streams metrics

### LINKED ISSUE #347: Kafka Streams Applications Lack Metrics
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure a Kafka Streams topology.
2. Configure a metric reporter.
3. Start Application with eager singleton initialization
4. Observe that there are no Kafka metrics

### Expected Behaviour

Kafka Stream metrics as well as metrics for the consumers and producers should appear in the registry.

### Actual Behaviour

Other metric binders contribute metrics, but nothing Kafka related appears.

### Environment Information

- **Operating System**: OSX 11.2.3
- **Micronaut Version:** 2.4.0
- **JDK Version:** 11.0.10.hs

### Example Application

_May provide later_

### PR DESCRIPTION
**Pull request by PhilHardwick**
fixes #347

### CODE REVIEW

**Comment by PhilHardwick** [comment]
This should (but doesn't yet) add more tags for streams and also deal with metrics like state which have a string value.

There's a bug in current Kafka Streams with getting the metric value of alive stream threads on start up which means it never gets registered - so that also needs to be worked around and then dropped when the fix is released in 2.8.1 or 3.0.0.

**Comment by ckosmowski** [comment]
What need to be done to get this into the project? I'd really like to see streams metrics as well.

**Comment by graemerocher** [comment]
PR needs some more work and to get the tests passing

**Comment by graemerocher** [comment]
Merged separately. Thanks for the contribution.

**Pull request closed without merging**
