### PR TITLE
Revert "build: Roll back to kafka 2.8.1, set version for minor switch…

### PR DESCRIPTION
**Pull request by sdelamo**
… to 3.6.x branch (#576)"

This reverts commit 02c6b143b1d676fc301ae7eeac08bd933cfeca39.

### CODE REVIEW

**Comment by sdelamo** [comment]
@dstepanov this is a PR which upgrades to Kafka for the Micronaut 4.

**Comment by wetted** [comment]
> @wetted this is a PR which upgrades to Kafka for the Micronaut 4. can you check why it fails?

The failure in all cases was `KafkaPartitionedErrorsSpec`. It's a flakey test and fails calling `"should correctly handle error strategies"()` with timeout issues in its `KafkaErrorsSpec` superclass. I reran each check where it failed and they all passed again.

**Review by wetted — APPROVED** [review]

**Comment by victorbonnet** [comment]
@sdelamo @wetted Thanks for the PR.
Do you guys know why we cannot merge and release it yet? 
Are we waiting for all PRs listed here: https://github.com/orgs/micronaut-projects/projects/14/views/1 ?

**Comment by wetted** [comment]
@victorbonnet correct, this can't be released yet. It will be part of the Micronaut 4 release.

**Comment by victorbonnet** [comment]
@wetted thanks for the update. 
Is this because of a blocker with the current version? I am wondering if we could already use that branch in our project.

**Comment by wetted** [comment]
ping @sdelamo Can you address this question. The PR is flagged for the 4.0.0 Release project, but is it really?

**Pull request closed without merging**
