### PR TITLE
Fix producer instrumentation

### PR DESCRIPTION
**Pull request by dstepanov**
Tracing wasn't working for producers

### CODE REVIEW

**Comment by graemerocher** [comment]
I think this is failing because this module is using an older version of Micronaut that uses older tracing libs

**Comment by dstepanov** [comment]
It strange that previous PR passed. Should I update tracing libs?

**Comment by graemerocher** [comment]
Give me some time to attempt some updates then I will try merge manually. Thanks

**Comment by graemerocher** [comment]
I am still in the process of upgrading the build and moving the CI to Github Actions, will follow up on this tomorrow

**Comment by graemerocher** [comment]
@dstepanov can you rebase? I have resolved the intermittent issues with the build and upgraded all the dependencies to the latest Kafka and Micronaut 

See https://github.com/micronaut-projects/micronaut-kafka/actions for the CI

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
