### PR TITLE
get GENERATED properties instead of RAW to allow env vars to override app settings

### PR DESCRIPTION
**Pull request by burtbeckwith**
Fixes https://github.com/micronaut-projects/micronaut-kafka/issues/179

### CODE REVIEW

**Review by graemerocher — CHANGES_REQUESTED** [review]
There are some check style failures it seems

**Comment by jens-guenther** [comment]
Are you sure that this one doesn't raise https://github.com/micronaut-projects/micronaut-core/issues/3210 again? You are just reverting the changes which fixed that issue. 

Although I think that using GENERATED is the right way of fetching the properties, I'm afraid 3210 pops up again. Would be great if someone could provide a test for all of these cases.

**Comment by graemerocher** [comment]
@jens-guenther you make a good point. Using `GENERATED` is definitely correctly but we need to check #3210 doesn't regress

**Comment by graemerocher** [comment]
created https://github.com/micronaut-projects/micronaut-kafka/issues/286 to track this

**Pull request merged**
