### PR TITLE
Remove annotation `@Internal` from class `JsonObjectSerde`

### PR DESCRIPTION
**Pull request by guillermocalvo**

### CODE REVIEW

**Comment by yawkat** [comment]
@dstepanov added you since you added the annotation

**Review by yawkat — APPROVED** [review]

**Comment by dstepanov** [comment]
Why does it need to be "public"?

**Comment by guillermocalvo** [comment]
> @dstepanov  Why does it need to be "public"?

Because documentation says it can be subclassed:

**Comment by dstepanov** [comment]
In what way would you do it?

**Comment by guillermocalvo** [comment]
> In what way would you do it?

I'd say either we stop discouraging users from using this class (ie. remove `@Internal`), or we stop advertising it in the documentation (ie. remove that little ℹ️ box).

It all depends on what motivated [the addition of this annotation](https://github.com/micronaut-projects/micronaut-kafka/pull/554/commits/b84bd9dc1bfddc18e411333b92be282b18887b08#diff-528a71a7f7b70b1aae7cc04ffe5e755d323277785626f6dfa9f8c19c12dc05fbR37) in the first place. @dstepanov What was the rationale behind it?

**Comment by dstepanov** [comment]
I just don’t understand how it can be extended and used to register anything. If you thinks the use case is valid go ahead and remove the internal. My motivation was to not expose internal classes as over API.

**Comment by guillermocalvo** [comment]
> My motivation was to not expose internal classes as over API.

If you believe this is really an internal class that shouldn't be directly subclassed by users, I can just remove that part of the guide. I'm good either way. Your call @dstepanov 

Thoughts? @yawkat @sdelamo

**Comment by yawkat** [comment]
it seems to me that to customize kafka serialization, subclassing JsonObjectSerde and overriding the read/write methods makes sense. but we have no sample of this.

@graemerocher you wrote this initially, do you remember how it's supposed to be used?

@henriquelsmti can you share what you do in your subclass?

**Comment by henriquelsmti** [comment]
@yawkat after somethings refatorations, we'r using JsonObjectSerde only on kafka streams.

**Comment by guillermocalvo** [comment]
There seem to be valid use cases for subclassing `JsonObjectSerde`. Shall we remove `@Internal` then?

@sdelamo @yawkat @dstepanov @graemerocher

**Comment by dstepanov** [comment]
If it’s a valid case then yes

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
