### PR TITLE
Fix 315 micronaut kafka listener commits messages at shutdown

### PR DESCRIPTION
**Pull request by seancarroll**
Extension to PR 350 which adds a couple of tests to validate change for defect micronaut-projects#315

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks will look at merging these changes soon

**Comment by seancarroll** [comment]
There might still be an issue when batch is set to true. When running `test batch shut down does not commit` by itself it passes however when its executed via `./gradlew build` it seems to fair more often than not. This might be timing related but given the batch path doesnt handle errors in the same way as the non-batch path I suspect that its more than a flaky test. I'm not sure what the appropriate way to handle errors in the batch side of things.

**Comment by seancarroll** [comment]
A larger issue with this change is that failed is never set back to false so offset isn't committed after re-delievery when an error occurred. I modified the `KafkaErrorHandlingSpec` to confirm this.

**Comment by seancarroll** [comment]
Committed a possible fix for the issue around not flipping failed back to false and attempting to enhance the `KafkaErrorHandlingSpec` test to validate we are committing offsets appropriately.

**Comment by seancarroll** [comment]
> Committed a possible fix for the issue around not flipping failed back to false and attempting to enhance the `KafkaErrorHandlingSpec` test to validate we are committing offsets appropriately.

This doesnt look to be an issue in the current codebase but I think batch is still problematic.

**Comment by graemerocher** [comment]
@seancarroll thanks will try merge this into the current codebase

**Comment by dstepanov** [comment]
Thanks for the contribution! I have incorporated your changes into https://github.com/micronaut-projects/micronaut-kafka/pull/441

**Pull request closed without merging**
