### PR TITLE
Pin Kafka version

### PR DESCRIPTION
**Pull request by alvarosanchez**

### CODE REVIEW

**Comment by sdelamo** [comment]
why do we need this?

**Comment by alvarosanchez** [comment]
Because otherwise we'll get PRs like #214 every single day.

We will upgrade the version eventually, but I'd like to publish a patch release with the current Kafka version.

**Comment by sdelamo** [comment]
Should we create issues to remember to unpin this versions ?

**Comment by alvarosanchez** [comment]
@sdelamo I created #216

**Review by ilopmar — APPROVED** [review]

**Pull request merged**
