### PR TITLE
Expose Consumer Assignment through ConsumerRegistry

### PR DESCRIPTION
**Pull request by brianwyka**
Expose each consumer's subscriptions and assignment through the `ConsumerRegistry` keyed by client id.  This information is hard to get since it can only be accessed from poll loop thread.

### CODE REVIEW

**Comment by graemerocher** [comment]
could you add a test?

**Comment by brianwyka** [comment]
Sure, I will do that.

**Comment by brianwyka** [comment]
@graemerocher, added a test as well as exposed the `subscriptions` (topics).

It seems that the subscriptions are available before the poll loop begins, and then the assignment becomes available within the poll loop after partitions have been assigned.  Although, I'm not exactly sure, precisely, when the assignment is happening.

**Comment by brianwyka** [comment]
I'm looking to use this functionality within a custom health indicator which determines kafka health based on the existence of consumers of specific topics.

**Comment by brianwyka** [comment]
This should be ready to go @graemerocher.  I can follow up with another feature request for the kafka consumer health indicator if it seems to be useful.

**Comment by brianwyka** [comment]
@graemerocher can we get this in the next Micronaut release?

**Pull request merged**
